services: 

  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    ports: 
      - "27017:27018"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  mysql: 
    image: mysql:8.0
    restart: always
    environment: 
      - MYSQL_DATABASE=ai-companion
      - MYSQL_ROOT_PASSWORD=prisma
    ports: 
      - "3307:3306"
    networks: 
      - prisma-network
    volumes: 
      - mysql_data:/var/lib/mysql
    logging: 
      options: 
        max-size: "10m"
        max-file: "3"
networks: 
  prisma-network: 
volumes: 
  mysql_data: 
